-- Alter DBS_SAL_INVOICE to add journey tracking metrics
ALTER TABLE DBS_SAL_INVOICE ADD (
    START_LAT NUMBER(12, 8),
    START_LONG NUMBER(12, 8),
    END_LAT NUMBER(12, 8),
    END_LONG NUMBER(12, 8),
    START_TIME TIMESTAMP WITH TIME ZONE,
    END_TIME TIMESTAMP WITH TIME ZONE,
    TOTAL_KILOMETERS NUMBER(10, 2),
    TOTAL_DURATION_MINUTES NUMBER(10, 2)
);
