-- =============================================================
-- CREATE DRIVERS TABLE (DBS_DRIVERS) & AUDIT TRIGGER
-- =============================================================

CREATE TABLE "DBS_DRIVERS" (
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
         MINVALUE 1 MAXVALUE 9999999999999999999999999999 
         INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
         
    "DRIVER_NAME"      VARCHAR2(255) NOT NULL,    -- اسم السائق
    "PHONE_NUMBER"     VARCHAR2(50)  NOT NULL,    -- رقم التليفون
    "LICENSE_NUMBER"   VARCHAR2(100),             -- رقم الرخصة
    "VEHICLE_NUMBER"   VARCHAR2(50)  NOT NULL,    -- رقم العربية (اللوحة)
    "VEHICLE_TYPE"     VARCHAR2(100),             -- نوع العربية
    "CBM"              NUMBER(10, 2),             -- السعة بالحجم (CBM)
    
    "STATUS"           VARCHAR2(10) DEFAULT '1' NOT NULL, -- الحالة: 1 نشط, 0 غير نشط
    
    "CREATED"          DATE DEFAULT SYSDATE,
    "CREATED_BY"       VARCHAR2(255),
    "UPDATED"          DATE,
    "UPDATED_BY"       VARCHAR2(255),
    
    CONSTRAINT "PK_DBS_DRIVERS" PRIMARY KEY ("ID"),
    CONSTRAINT "UK_DBS_DRIVERS_PHONE" UNIQUE ("PHONE_NUMBER")
);

-- Index for phone number search performance
CREATE INDEX "IDX_DRIVERS_PHONE" ON "DBS_DRIVERS" ("PHONE_NUMBER");

-- =============================================================
-- AUDIT TRIGGER (BEFORE INSERT OR UPDATE)
-- =============================================================
CREATE OR REPLACE EDITIONABLE TRIGGER "DBS_DRIVERS_BIU"
BEFORE INSERT OR UPDATE ON "DBS_DRIVERS"
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED := SYSDATE;
        :NEW.CREATED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
    END IF;
    
    :NEW.UPDATED := SYSDATE;
    :NEW.UPDATED_BY := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), USER);
END;
/
ALTER TRIGGER "DBS_DRIVERS_BIU" ENABLE;
