-- Generated by ORDS REST Data Services 25.2.1.r1942034
-- Schema: ERP_STOCK  Date: Sat Jul 04 02:40:00 2026 
--

DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'app',
      p_auto_rest_auth      => FALSE);

  -- =============================================================
  -- MODULE: StockCount
  -- =============================================================
  BEGIN
    ORDS.DELETE_MODULE(p_module_name => 'StockCount');
  EXCEPTION
    WHEN OTHERS THEN NULL;
  END;

  ORDS.DEFINE_MODULE(
      p_module_name    => 'StockCount',
      p_base_path      => '/StockCount/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  -- 2.1 Template: GetActiveSessions (GET)
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'StockCount',
      p_pattern        => 'GetActiveSessions',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'StockCount',
      p_pattern        => 'GetActiveSessions',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_header_value    VARCHAR2(4000);
    l_bearer_token    VARCHAR2(4000);
    l_token           APEX_JWT.T_TOKEN;
    l_user_object     APEX_JSON.T_VALUES;
    l_phone           VARCHAR2(200);
    l_user_type       VARCHAR2(200);
    l_user_id         NUMBER;
    l_count           NUMBER := 0;
    
BEGIN
    -- Authentication Check
    l_header_value := OWA_UTIL.get_cgi_env(''Authorization'');
    IF l_header_value IS NULL OR INSTR(l_header_value, ''Bearer '') != 1 THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''يرجى تسجيل الدخول أولاً'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Authentication required'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''TOKEN_REQUIRED'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 401;
        RETURN;
    END IF;

    l_bearer_token := SUBSTR(l_header_value, 8);
    BEGIN
        l_token := APEX_JWT.DECODE(
            p_value => l_bearer_token,
            p_signature_key => SYS.UTL_RAW.CAST_TO_RAW(''secretKey'')
        );
        APEX_JWT.VALIDATE(p_token => l_token, p_iss => ''ORDS'');
        APEX_JSON.PARSE(l_user_object, l_token.payload);
        l_phone := APEX_JSON.GET_VARCHAR2(p_path => ''sub'', p_values => l_user_object);
        l_user_type := APEX_JSON.GET_VARCHAR2(p_path => ''aud'', p_values => l_user_object);
    EXCEPTION
        WHEN OTHERS THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''جلسة غير صالحة'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Invalid token'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''INVALID_TOKEN'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 401;
            RETURN;
    END;

    -- Verify user login (STATUS = 1 as number)
    BEGIN
        SELECT USER_ID INTO l_user_id
        FROM VW_API_ENTRY_LOGIN
        WHERE PHONE_NUMBER = l_phone AND TYPE_LOGIN = l_user_type AND STATUS = 1 AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''المستخدم غير موجود'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''User not found'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''USER_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    :status := 200;
    APEX_JSON.open_object;
    APEX_JSON.write(''status'', ''success'', p_write_null => TRUE);
    APEX_JSON.write(''messageAr'', ''تم جلب وراديات الجرد بنجاح'', p_write_null => TRUE);
    APEX_JSON.write(''messageEn'', ''Stock count sessions retrieved successfully'', p_write_null => TRUE);
    
    APEX_JSON.open_array(''sessions'');

    FOR rec IN (
        SELECT
            M.ID,
            M.AUTO_NUMBER,
            TO_CHAR(M.COUNT_DATE, ''YYYY-MM-DD'') AS COUNT_DATE,
            M.DESCRIPTION
        FROM DBS_STOCK_COUNT_MST M
        WHERE M.STATUS = ''1'' -- Active count sessions
        ORDER BY M.ID DESC
    ) LOOP
        l_count := l_count + 1;
        
        APEX_JSON.open_object;
        APEX_JSON.write(''id'',          rec.ID,          p_write_null => TRUE);
        APEX_JSON.write(''autoNumber'',  rec.AUTO_NUMBER, p_write_null => TRUE);
        APEX_JSON.write(''countDate'',   rec.COUNT_DATE,  p_write_null => TRUE);
        APEX_JSON.write(''description'', rec.DESCRIPTION, p_write_null => TRUE);
        APEX_JSON.close_object;
    END LOOP;

    APEX_JSON.close_array;
    APEX_JSON.write(''total'', l_count, p_write_null => TRUE);
    APEX_JSON.close_object;

EXCEPTION
    WHEN OTHERS THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''حدث خطأ في النظام'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''System error: '' || SQLERRM, p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''SYSTEM_ERROR'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 500;
END;');

  -- 2.2 Template: SaveCountDetail (POST)
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'StockCount',
      p_pattern        => 'SaveCountDetail',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'StockCount',
      p_pattern        => 'SaveCountDetail',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_header_value    VARCHAR2(4000);
    l_bearer_token    VARCHAR2(4000);
    l_token           APEX_JWT.T_TOKEN;
    l_user_object     APEX_JSON.T_VALUES;
    l_phone           VARCHAR2(200);
    l_user_type       VARCHAR2(200);
    l_user_id         NUMBER;
    
    l_master_id       NUMBER;
    l_item_id         NUMBER;
    l_qty_counted     NUMBER;
    l_item_code       VARCHAR2(100);
    l_location_id     NUMBER;
    l_notes           VARCHAR2(1000);
    l_status          VARCHAR2(10);
    
BEGIN
    -- Authentication Check
    l_header_value := OWA_UTIL.get_cgi_env(''Authorization'');
    IF l_header_value IS NULL OR INSTR(l_header_value, ''Bearer '') != 1 THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''يرجى تسجيل الدخول أولاً'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Authentication required'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''TOKEN_REQUIRED'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 401;
        RETURN;
    END IF;

    l_bearer_token := SUBSTR(l_header_value, 8);
    BEGIN
        l_token := APEX_JWT.DECODE(
            p_value => l_bearer_token,
            p_signature_key => SYS.UTL_RAW.CAST_TO_RAW(''secretKey'')
        );
        APEX_JWT.VALIDATE(p_token => l_token, p_iss => ''ORDS'');
        APEX_JSON.PARSE(l_user_object, l_token.payload);
        l_phone := APEX_JSON.GET_VARCHAR2(p_path => ''sub'', p_values => l_user_object);
        l_user_type := APEX_JSON.GET_VARCHAR2(p_path => ''aud'', p_values => l_user_object);
    EXCEPTION
        WHEN OTHERS THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''جلسة غير صالحة'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Invalid token'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''INVALID_TOKEN'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 401;
            RETURN;
    END;

    -- Get User ID (STATUS = 1 as number)
    BEGIN
        SELECT USER_ID INTO l_user_id
        FROM VW_API_ENTRY_LOGIN
        WHERE PHONE_NUMBER = l_phone AND TYPE_LOGIN = l_user_type AND STATUS = 1 AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''المستخدم غير موجود'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''User not found'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''USER_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    -- Read POST inputs
    l_master_id   := TO_NUMBER(:masterId);
    l_qty_counted := TO_NUMBER(:qtyCounted);
    l_item_code   := :itemCode;
    l_location_id := TO_NUMBER(:location);
    l_notes       := :notes;

    IF l_master_id IS NULL OR l_qty_counted IS NULL OR l_qty_counted < 0 OR l_item_code IS NULL THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''المدخلات غير كاملة أو غير صحيحة'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Missing or invalid parameters'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''INVALID_INPUT'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 400;
        RETURN;
    END IF;

    -- Verify stock count session is still open
    BEGIN
        SELECT STATUS INTO l_status
        FROM DBS_STOCK_COUNT_MST
        WHERE ID = l_master_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''جلسة الجرد المحددة غير موجودة بالنظام'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Stock count session not found'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''SESSION_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    IF l_status = ''0'' THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''وردية الجرد مغلقة حالياً ولا يمكن التعديل عليها'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Stock count session is closed'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''SESSION_CLOSED'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 400;
        RETURN;
    END IF;

    -- Resolve Item ID
    BEGIN
        SELECT ID INTO l_item_id
        FROM DBS_STOCK_ITEMS
        WHERE ITEM_CODE = l_item_code 
           OR BARCODE = l_item_code 
           OR TO_CHAR(ID) = l_item_code
           AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''هذا الصنف غير مسجل بالنظام'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Item code not found'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''ITEM_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    -- Save/Insert count details
    INSERT INTO DBS_STOCK_COUNT_DTL (
        DBS_STOCK_COUNT_MST_ID,
        DBS_STOCK_ITEMS_ID,
        USER_ID,
        QTY_COUNTED,
        DBS_STOCK_STORE_DTL_LOC_ID,
        NOTES,
        COUNT_DATE
    ) VALUES (
        l_master_id,
        l_item_id,
        l_user_id,
        l_qty_counted,
        l_location_id,
        l_notes,
        SYSDATE
    );
    COMMIT;

    APEX_JSON.open_object;
    APEX_JSON.write(''status'', ''success'', p_write_null => TRUE);
    APEX_JSON.write(''messageAr'', ''تم تسجيل الصنف المجرود بنجاح'', p_write_null => TRUE);
    APEX_JSON.write(''messageEn'', ''Item count recorded successfully'', p_write_null => TRUE);
    APEX_JSON.close_object;
    :status := 200;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''حدث خطأ في النظام'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''System error: '' || SQLERRM, p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''SYSTEM_ERROR'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 500;
END;');

  -- 2.3 Template: GetSessionDetails (GET)
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'StockCount',
      p_pattern        => 'GetSessionDetails',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'StockCount',
      p_pattern        => 'GetSessionDetails',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_header_value    VARCHAR2(4000);
    l_bearer_token    VARCHAR2(4000);
    l_token           APEX_JWT.T_TOKEN;
    l_user_object     APEX_JSON.T_VALUES;
    l_phone           VARCHAR2(200);
    l_user_type       VARCHAR2(200);
    l_user_id         NUMBER;
    l_master_id       NUMBER;
    l_count           NUMBER := 0;
    
BEGIN
    -- Authentication Check
    l_header_value := OWA_UTIL.get_cgi_env(''Authorization'');
    IF l_header_value IS NULL OR INSTR(l_header_value, ''Bearer '') != 1 THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''يرجى تسجيل الدخول أولاً'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Authentication required'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''TOKEN_REQUIRED'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 401;
        RETURN;
    END IF;

    l_bearer_token := SUBSTR(l_header_value, 8);
    BEGIN
        l_token := APEX_JWT.DECODE(
            p_value => l_bearer_token,
            p_signature_key => SYS.UTL_RAW.CAST_TO_RAW(''secretKey'')
        );
        APEX_JWT.VALIDATE(p_token => l_token, p_iss => ''ORDS'');
        APEX_JSON.PARSE(l_user_object, l_token.payload);
        l_phone := APEX_JSON.GET_VARCHAR2(p_path => ''sub'', p_values => l_user_object);
        l_user_type := APEX_JSON.GET_VARCHAR2(p_path => ''aud'', p_values => l_user_object);
    EXCEPTION
        WHEN OTHERS THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''جلسة غير صالحة'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Invalid token'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''INVALID_TOKEN'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 401;
            RETURN;
    END;

    -- Get User ID (STATUS = 1 as number)
    BEGIN
        SELECT USER_ID INTO l_user_id
        FROM VW_API_ENTRY_LOGIN
        WHERE PHONE_NUMBER = l_phone AND TYPE_LOGIN = l_user_type AND STATUS = 1 AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''المستخدم غير موجود'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''User not found'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''USER_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    l_master_id := TO_NUMBER(:masterId);

    IF l_master_id IS NULL THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''معرف وردية الجرد مطلوب'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Count session ID is required'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''MISSING_PARAM'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 400;
        RETURN;
    END IF;

    :status := 200;
    APEX_JSON.open_object;
    APEX_JSON.write(''status'', ''success'', p_write_null => TRUE);
    APEX_JSON.write(''messageAr'', ''تم جلب تفاصيل الجرد بنجاح'', p_write_null => TRUE);
    APEX_JSON.write(''messageEn'', ''Count session details retrieved successfully'', p_write_null => TRUE);
    
    APEX_JSON.open_array(''details'');

    FOR rec IN (
        SELECT
            D.ID               AS DETAIL_ID,
            D.DBS_STOCK_ITEMS_ID AS ITEM_ID,
            I.ITEM_CODE,
            I.NAME_AR          AS ITEM_NAME,
            I.ITEM_SIDE,
            D.QTY_COUNTED      AS QTY_COUNTED,
            D.DBS_STOCK_STORE_DTL_LOC_ID AS LOCATION_ID,
            (SELECT l.NAME_AR FROM DBS_STOCK_STORE_DTL_LOC l WHERE l.ID = D.DBS_STOCK_STORE_DTL_LOC_ID) AS LOCATION_NAME,
            D.NOTES,
            TO_CHAR(D.COUNT_DATE, ''YYYY-MM-DD HH24:MI:SS'') AS COUNT_DATE
        FROM DBS_STOCK_COUNT_DTL D
        JOIN DBS_STOCK_ITEMS I ON I.ID = D.DBS_STOCK_ITEMS_ID
        WHERE D.DBS_STOCK_COUNT_MST_ID = l_master_id
          AND D.USER_ID = l_user_id
        ORDER BY D.ID DESC
    ) LOOP
        l_count := l_count + 1;
        
        APEX_JSON.open_object;
        APEX_JSON.write(''detailId'',    rec.DETAIL_ID,   p_write_null => TRUE);
        APEX_JSON.write(''itemId'',      rec.ITEM_ID,     p_write_null => TRUE);
        APEX_JSON.write(''itemCode'',    rec.ITEM_CODE,   p_write_null => TRUE);
        APEX_JSON.write(''itemName'',    rec.ITEM_NAME,   p_write_null => TRUE);
        APEX_JSON.write(''itemSide'',    rec.ITEM_SIDE,   p_write_null => TRUE);
        APEX_JSON.write(''qtyCounted'',  rec.QTY_COUNTED, p_write_null => TRUE);
        APEX_JSON.write(''location'',    rec.LOCATION_NAME, p_write_null => TRUE);
        APEX_JSON.write(''locationId'',  rec.LOCATION_ID, p_write_null => TRUE);
        APEX_JSON.write(''notes'',       rec.NOTES,       p_write_null => TRUE);
        APEX_JSON.write(''countDate'',   rec.COUNT_DATE,  p_write_null => TRUE);
        APEX_JSON.close_object;
    END LOOP;

    APEX_JSON.close_array;
    APEX_JSON.write(''total'', l_count, p_write_null => TRUE);
    APEX_JSON.close_object;

EXCEPTION
    WHEN OTHERS THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''حدث خطأ في النظام'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''System error: '' || SQLERRM, p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''SYSTEM_ERROR'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 500;
END;');

  -- 2.4 Template: UpdateCountQty (POST)
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'StockCount',
      p_pattern        => 'UpdateCountQty',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'StockCount',
      p_pattern        => 'UpdateCountQty',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_header_value    VARCHAR2(4000);
    l_bearer_token    VARCHAR2(4000);
    l_token           APEX_JWT.T_TOKEN;
    l_user_object     APEX_JSON.T_VALUES;
    l_phone           VARCHAR2(200);
    l_user_type       VARCHAR2(200);
    l_user_id         NUMBER;
    
    l_detail_id       NUMBER;
    l_qty_counted     NUMBER;
    l_notes           VARCHAR2(1000);
    l_count           NUMBER;
    l_master_id       NUMBER;
    l_status          VARCHAR2(10);
    
BEGIN
    -- Authentication Check
    l_header_value := OWA_UTIL.get_cgi_env(''Authorization'');
    IF l_header_value IS NULL OR INSTR(l_header_value, ''Bearer '') != 1 THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''يرجى تسجيل الدخول أولاً'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Authentication required'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''TOKEN_REQUIRED'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 401;
        RETURN;
    END IF;

    l_bearer_token := SUBSTR(l_header_value, 8);
    BEGIN
        l_token := APEX_JWT.DECODE(
            p_value => l_bearer_token,
            p_signature_key => SYS.UTL_RAW.CAST_TO_RAW(''secretKey'')
        );
        APEX_JWT.VALIDATE(p_token => l_token, p_iss => ''ORDS'');
        APEX_JSON.PARSE(l_user_object, l_token.payload);
        l_phone := APEX_JSON.GET_VARCHAR2(p_path => ''sub'', p_values => l_user_object);
        l_user_type := APEX_JSON.GET_VARCHAR2(p_path => ''aud'', p_values => l_user_object);
    EXCEPTION
        WHEN OTHERS THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''جلسة غير صالحة'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Invalid token'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''INVALID_TOKEN'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 401;
            RETURN;
    END;

    -- Get User ID (STATUS = 1 as number)
    BEGIN
        SELECT USER_ID INTO l_user_id
        FROM VW_API_ENTRY_LOGIN
        WHERE PHONE_NUMBER = l_phone AND TYPE_LOGIN = l_user_type AND STATUS = 1 AND ROWNUM = 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''المستخدم غير موجود'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''User not found'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''USER_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    -- Read parameters
    l_detail_id   := TO_NUMBER(:detailId);
    l_qty_counted := TO_NUMBER(:qtyCounted);
    l_notes       := :notes;

    IF l_detail_id IS NULL OR l_qty_counted IS NULL OR l_qty_counted < 0 THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''المدخلات غير كاملة أو غير صحيحة'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Missing or invalid parameters'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''INVALID_INPUT'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 400;
        RETURN;
    END IF;

    -- Verify stock count details row exists and belongs to this user
    BEGIN
        SELECT DBS_STOCK_COUNT_MST_ID INTO l_master_id
        FROM DBS_STOCK_COUNT_DTL
        WHERE ID = l_detail_id AND USER_ID = l_user_id;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            APEX_JSON.open_object;
            APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
            APEX_JSON.write(''messageAr'', ''سجل الجرد غير موجود أو لا يخصك تعديله'', p_write_null => TRUE);
            APEX_JSON.write(''messageEn'', ''Count detail not found or not owned by you'', p_write_null => TRUE);
            APEX_JSON.write(''errorCode'', ''DETAIL_NOT_FOUND'', p_write_null => TRUE);
            APEX_JSON.close_object;
            :status := 404;
            RETURN;
    END;

    -- Verify stock count session is still open
    SELECT STATUS INTO l_status
    FROM DBS_STOCK_COUNT_MST
    WHERE ID = l_master_id;

    IF l_status = ''0'' THEN
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''وردية الجرد مغلقة حالياً ولا يمكن التعديل عليها'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''Stock count session is closed'', p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''SESSION_CLOSED'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 400;
        RETURN;
    END IF;

    -- Update count quantity
    UPDATE DBS_STOCK_COUNT_DTL
    SET QTY_COUNTED = l_qty_counted,
        NOTES = COALESCE(l_notes, NOTES)
    WHERE ID = l_detail_id;
    COMMIT;

    APEX_JSON.open_object;
    APEX_JSON.write(''status'', ''success'', p_write_null => TRUE);
    APEX_JSON.write(''messageAr'', ''تم تعديل الكمية المجرودة بنجاح'', p_write_null => TRUE);
    APEX_JSON.write(''messageEn'', ''Counted quantity updated successfully'', p_write_null => TRUE);
    APEX_JSON.close_object;
    :status := 200;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        APEX_JSON.open_object;
        APEX_JSON.write(''status'', ''error'', p_write_null => TRUE);
        APEX_JSON.write(''messageAr'', ''حدث خطأ في النظام'', p_write_null => TRUE);
        APEX_JSON.write(''messageEn'', ''System error: '' || SQLERRM, p_write_null => TRUE);
        APEX_JSON.write(''errorCode'', ''SYSTEM_ERROR'', p_write_null => TRUE);
        APEX_JSON.close_object;
        :status := 500;
END;');

  COMMIT;
END;
